# -*- coding: utf-8 -*-
"""2.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t7ecu9HfN04L0nCpYIsBvicOR7rzucx-
"""

import pandas as pd

"""After importing pandas, we are going to utilize this CSV file to get all the data related to baby names within the US

https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv
"""

baby_names = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv")

"""Convert the CSV file that we grab online and feed into the following function

```
pd.read_csv("URL")
```
This will parse the CSV file into a Pandas DataFrame
Next we'll display the first 10 entries of the DataFrame


"""

baby_names.head(10)

"""Pandas core object called DataFrame allow us to access several methods that not only allow us to read the data, but also to create, manipulate and delete data within the DataFrame"""

print(type(baby_names))

"""Using the following function


```
DataFrame.sort_values("Coloum Name", ascending=0)
```
We are able to sort out DataFrame based on a certain coloumn, it can display names and numbers in ascending order


"""

baby_names.sort_values("Count", ascending=0).head(5)

"""This following allows us to group the rows together (Since rows and baby names are split, look at David for example). We group the rows based on baby names and then sort by count.

This allows us to get the true most popular baby name, which is Jacob!
"""

popular_names = baby_names.groupby("Name").sum()
popular_names_asc = popular_names.sort_values("Count", ascending=0)
popular_names_asc["Count"].head(10)