# -*- coding: utf-8 -*-
"""2.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H4FN8aGzPQkQWyQvLiPD0Timsphp8Zrm

Cleaning a messy real estate dataset by handelling missing values and outliers. Utilize Pandas to load the dataset, identify missing data, and perform data cleaning operations such as imputation and outlier removal.

Importing Pandas and giving it the alias of pd, provide several functions to read, create, update, and delete data

Import Numpy allows us to perform powerfull operations on our data

Import scipy allows us to get the Z score for our data
"""

import pandas as pd
import numpy as np
from scipy import stats

"""Call upon the code to read our messy real estate data set

```
pd.read_csv("URL")
```


"""

df = pd.read_csv("./sample_data/california_housing_mess.csv")

"""Display the first 10 rows/entries of our data set"""

df.head(10)

"""To find out if your dataset has zeros, or outliers, we can use the following code, to organize our dataset and see if any values are clear outliers.

```
sort_values("coloum name")
```

To find out if your data has NaN or null values, we can use the following code that goes through the dataset and prints if a row has a null value along with its column.

```
df.isnull()
```

"""

df.sort_values("median_house_value", ascending=True).head(20)

print(df.isnull())

"""In order to clean up our null values or NaN, we can call the following function that will not only find them, but will replace them with a value that we want



```
df.fillna(value, inplace=True)
```


"""

df.fillna(123, inplace=True)
df.head(10)

"""In order to remove outliers, we need to calculate the [z-score](https://www.investopedia.com/terms/z/zscore.asp) which allows us to find outliers and remove them using the following code

```
df[(np.abs(stats.zscore(df)) < 3).all(axis=1)]
```


"""

df[(np.abs(stats.zscore(df)) < 3).all(axis=1)]

z = np.abs(stats.zscore(df_miss))
df_fixed = df_miss[(z < 1.25).all(axis=1)]
print(z)
df_fixed.head(10)