# -*- coding: utf-8 -*-
"""Find Pair with Target Sum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CNghlvNeoH12Wx4xs3hP-mz5gqR2I-V7

https://colab.research.google.com
"""

def find_pair(arr, target_sum):

  left_index = 0
  right_index = len(arr) - 1

  while (left_index - right_index):

    current_sum = arr[left_index] + arr[right_index]

    if current_sum == target_sum:

      return [left_index, right_index]

    if current_sum < target_sum:

      left_index += 1

    else: 

      right_index -= 1
  
  return [-1, -1]

find_pair([2, 4, 6, 8, 12], 10)