# -*- coding: utf-8 -*-
"""Remove Targets from Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-XsfxmCbRgKPz6HG0EBbhwPSn-aTcylt

https://colab.research.google.com
"""

def remove_target(arr, target):

  next_element_index = 0

  for element_index in range(len(arr)):

    if arr[element_index] != target:
      
      arr[next_element_index] = arr[element_index]

      next_element_index += 1

  return next_element_index 

remove_target([2, 2, 5, 6, 8, 8, 3], 8)