# -*- coding: utf-8 -*-
"""Remove Duplicates from List.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BXyh_1h3UVRq_R9Pi5OevxBF1lX7sRVb
"""

def remove_duplicates(arr):

  next_non_duplicate_index = 1

  i = 1

  while (i < len(arr)):

    if (arr[next_non_duplicate_index - 1] != arr[i]):

      arr[next_non_duplicate_index] = arr[i]

      next_non_duplicate_index += 1

    i += 1

  return next_non_duplicate_index

remove_duplicates([1, 3, 3, 4, 6, 7, 7])