# -*- coding: utf-8 -*-
"""Square a Sorted Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NJ7EBDb4i_cnWaC32iSl9Wbk-9oEaRKG

https://colab.research.google.com
"""

def square(arr):

  left_index = 0
  right_index = len(arr) - 1
  squares = [0 for element in range(len(arr))]
  highest_square_index = len(arr) - 1

  while left_index <= right_index: 

    left_square = arr[left_index] * arr[left_index]
    right_square = arr[right_index] * arr[right_index]

    if left_square > right_square:

      squares[highest_square_index] = left_square
      left_index += 1

    else: 

      squares[highest_square_index] = right_square
      right_index -= 1

    highest_square_index -= 1

  return squares 

square([-1, 2, 2, 5, 7])