# -*- coding: utf-8 -*-
"""2.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10VLdSObSnSivg_G68NmHN6eK_7zi_qtj

Analyze a dataset of tweets to find the most frequent hashtags and mentions. Use
Pandas to load and manipulate the dataset, and then generate statistics to identify the most commonly used hashtags and mentions.

Importing pandas, and giving it an alias of pd
"""

import pandas as pd

"""We used [Mockaroo](https://www.mockaroo.com/) to generate our fake data. If you'd like, and I highly suggest it, look at the Twitter API, learn how to create a developer account, and get real data from that API.

But for the simplicity of this project, we're going to use Mockaroo to get fake data and work with that. With our generated data, we are going to read it and parse it into a Pandas Data frame using

**Remeber to add the .csv file into our Google CoLabs file directors, this is located on the left hand side of the website. Keep in mind it remains per session, meaning if you leave the page, then you'll have to add it again!**

```
# pd.read_csv("URL / Local Path")
```


"""

df = pd.read_csv("./sample_data/MOCK_DATA.csv")

print(type(df))

"""The following function allows us to read our csv in a tabular format. Makes it more organized, and understanding!"""

df.head()

"""In order to organize the data and find the most commonly used hashtags / mentions, we'll need to use the following function

```
# df["Column Name"].value_counts()
```

This will take a column, and then count how many values appear in the DataFrame, it'll organize as well based on the hightest number in ascending order!

"""

df['hashtag'].value_counts()

df["mentions"].value_counts()