# -*- coding: utf-8 -*-
"""Find Maximum Sum Subarray of Size K.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Va_sr4GBENUZnvtIKI8k1tHJ9-3LlykS

https://colab.research.google.com
"""

def find_max_array(k, arr): 

  max_sum, window_sum = 0, 0
  start_index = 0

  for element_index in range(len(arr)): 

      window_sum += arr[element_index]

      if element_index + 1 >= k:

        max_sum = max(max_sum, window_sum)

        window_sum -= arr[start_index]

        start_index += 1

  return max_sum 

find_max_array(2, [1, 4, 8, 2])