# -*- coding: utf-8 -*-
"""Smallest Subarray with Given Sum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ywuDHkT6ceVJNoGFf9WgUknawr-ZbhAp

https://colab.research.google.com
"""

import math 

def find_smallest_array(s, arr): 

  window_sum = 0
  min_length = math.inf
  start_index = 0

  for element_index in range(0, len(arr)):
    window_sum += arr[element_index]

    while window_sum >= s:

      min_length = min(min_length, element_index - start_index + 1)
      window_sum -= arr[start_index]
      start_index += 1

  if min_length == math.inf:
    return 0

  return min_length

find_smallest_array(4, [2, 4, 3, 9])